apiVersion: run.tanzu.vmware.com/v1alpha3
kind: ClusterBootstrap
metadata:
  name: management-cluster
  namespace: tkg-system
spec:
  clusterClass: tkg-vsphere-default-v1.0.0
  clusterName: management-cluster
  topology:
    class: tkg-vsphere-default-v1.0.0
    version: v1.27.5+vmware.1-tkg.1
    controlPlane:
      replicas: 3
      metadata:
        annotations:
          cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "3"
          cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "3"
    workers:
      machineDeployments:
      - class: tkg-worker
        name: md-0
        replicas: 2
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "2"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "10"
    variables:
    - name: vmClass
      value: best-effort-medium
    - name: storageClass
      value: default
    - name: defaultStorageClass
      value: default
    - name: nodePoolLabels
      value:
      - key: cluster-role
        value: management
    - name: nodePoolTaints
      value:
      - key: node-role.kubernetes.io/control-plane
        value: ""
        effect: NoSchedule
    - name: trust
      value:
        additionalTrustedCAs:
        - name: corporate-ca
          data: |
            -----BEGIN CERTIFICATE-----
            # Add your corporate CA certificate here
            -----END CERTIFICATE-----
    - name: identityManagement
      value:
        type: oidc
        oidc:
          issuerURL: https://your-oidc-provider.com
          clientID: kubernetes
          usernameClaim: email
          groupsClaim: groups
    - name: network
      value:
        cni:
          name: antrea
        serviceDomain: cluster.local
        pods:
          cidrBlocks:
          - 192.168.0.0/16
        services:
          cidrBlocks:
          - 10.96.0.0/12
    - name: controlPlaneEndpoint
      value:
        host: management-cluster.example.com
        port: 6443
    - name: auditLogging
      value:
        enabled: true
        config:
          apiVersion: audit.k8s.io/v1
          kind: Policy
          rules:
          - level: RequestResponse
            resources:
            - group: ""
              resources: ["pods", "services"]
    - name: podSecurityStandard
      value:
        audit: restricted
        warn: restricted
        enforce: baseline
        deactivated: false
    - name: apiServerEndpoint
      value:
        host: management-cluster.example.com
        port: 6443
    - name: aviAPIServerHAProvider
      value: true
    - name: vcenter
      value:
        cloneMode: fullClone
        datacenter: "/datacenter1"
        datastore: "/datacenter1/datastore/datastore1"
        folder: "/datacenter1/vm/tkg"
        network: "/datacenter1/network/VM Network"
        resourcePool: "/datacenter1/host/cluster1/Resources/tkg"
        server: vcenter.example.com
        storagePolicyID: ""
        template: "/datacenter1/vm/tkg/ubuntu-2004-kube-v1.27.5+vmware.1-tkg.1"
        tlsThumbprint: "XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX"
---
apiVersion: v1
kind: Secret
metadata:
  name: management-cluster-vsphere-creds
  namespace: tkg-system
type: Opaque
stringData:
  username: ${VSPHERE_USERNAME}
  password: ${VSPHERE_PASSWORD}