apiVersion: v1
kind: ConfigMap
metadata:
  name: management-cluster-config
  namespace: tkg-system
data:
  cluster-config.yaml: |
    #! ---------------------------------------------------------------------
    #! Basic cluster creation configuration
    #! ---------------------------------------------------------------------
    
    CLUSTER_NAME: tkg-mgmt-cluster
    CLUSTER_PLAN: prod
    INFRASTRUCTURE_PROVIDER: vsphere
    ENABLE_CEIP_PARTICIPATION: "false"
    ENABLE_AUDIT_LOGGING: "true"
    CLUSTER_CIDR: 100.96.0.0/11
    SERVICE_CIDR: 100.64.0.0/13
    
    #! ---------------------------------------------------------------------
    #! vSphere configuration
    #! ---------------------------------------------------------------------
    
    VSPHERE_SERVER: vcenter.yourdomain.com
    VSPHERE_USERNAME: administrator@vsphere.local
    VSPHERE_PASSWORD: <encoded:Vk13YXJlMSE=>
    VSPHERE_DATACENTER: /Datacenter
    VSPHERE_RESOURCE_POOL: /Datacenter/host/Cluster/Resources
    VSPHERE_DATASTORE: /Datacenter/datastore/vsanDatastore
    VSPHERE_FOLDER: /Datacenter/vm/tkg
    VSPHERE_NETWORK: /Datacenter/network/VM Network
    VSPHERE_SSH_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC...
    
    #! ---------------------------------------------------------------------
    #! Node configuration
    #! ---------------------------------------------------------------------
    
    # Control plane nodes
    VSPHERE_CONTROL_PLANE_ENDPOINT: 192.168.1.10
    VSPHERE_CONTROL_PLANE_NUM_CPUS: 4
    VSPHERE_CONTROL_PLANE_DISK_GIB: 40
    VSPHERE_CONTROL_PLANE_MEM_MIB: 8192
    
    # Worker nodes
    VSPHERE_WORKER_NUM_CPUS: 4
    VSPHERE_WORKER_DISK_GIB: 40
    VSPHERE_WORKER_MEM_MIB: 8192
    
    #! ---------------------------------------------------------------------
    #! Machine Health Check configuration
    #! ---------------------------------------------------------------------
    
    ENABLE_MHC: "true"
    MHC_UNKNOWN_STATUS_TIMEOUT: 5m
    MHC_FALSE_STATUS_TIMEOUT: 12m
    
    #! ---------------------------------------------------------------------
    #! Common configuration
    #! ---------------------------------------------------------------------
    
    TKG_CUSTOM_IMAGE_REPOSITORY: ""
    TKG_CUSTOM_IMAGE_REPOSITORY_CA_CERTIFICATE: ""
    TKG_HTTP_PROXY: ""
    TKG_HTTPS_PROXY: ""
    TKG_NO_PROXY: ""
    
    #! ---------------------------------------------------------------------
    #! Antrea CNI configuration
    #! ---------------------------------------------------------------------
    
    ANTREA_NO_SNAT: "false"
    ANTREA_TRAFFIC_ENCAP_MODE: "encap"
    ANTREA_PROXY: "true"
    ANTREA_POLICY: "true"
    ANTREA_TRACEFLOW: "true"
    
    #! ---------------------------------------------------------------------
    #! Identity management configuration
    #! ---------------------------------------------------------------------
    
    IDENTITY_MANAGEMENT_TYPE: "none"
    LDAP_BIND_DN: ""
    LDAP_BIND_PASSWORD: ""
    LDAP_HOST: ""
    LDAP_USER_SEARCH_BASE_DN: ""
    LDAP_USER_SEARCH_FILTER: ""
    LDAP_USER_SEARCH_USERNAME: ""
    LDAP_GROUP_SEARCH_BASE_DN: ""
    LDAP_GROUP_SEARCH_FILTER: ""
    LDAP_GROUP_SEARCH_USER_ATTRIBUTE: ""
    LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
    LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: ""
    LDAP_ROOT_CA_DATA_B64: ""
    OIDC_ISSUER_URL: ""
    OIDC_USERNAME_CLAIM: ""
    OIDC_GROUPS_CLAIM: ""
    OIDC_CLIENT_ID: ""
    OIDC_CLIENT_SECRET: ""
    OIDC_SCOPES: ""
    OIDC_CA_DATA_B64: ""
    
    #! ---------------------------------------------------------------------
    #! Pinniped configuration
    #! ---------------------------------------------------------------------
    
    SUPERVISOR_ENDPOINT: ""
    SUPERVISOR_CA_BUNDLE_DATA: ""
    
    #! ---------------------------------------------------------------------
    #! Control plane configuration
    #! ---------------------------------------------------------------------
    
    CONTROL_PLANE_MACHINE_COUNT: 3
    WORKER_MACHINE_COUNT: 2
    
    #! ---------------------------------------------------------------------
    #! Kubernetes version
    #! ---------------------------------------------------------------------
    
    KUBERNETES_VERSION: "v1.28.8+vmware.1"
    
    #! ---------------------------------------------------------------------
    #! Security configuration
    #! ---------------------------------------------------------------------
    
    ENABLE_DEFAULT_STORAGE_CLASS: "true"
    ENABLE_AUTOSCALER: "false"
    AUTOSCALER_MAX_NODES_TOTAL: "0"
    AUTOSCALER_SCALE_DOWN_DELAY_AFTER_ADD: "10m"
    AUTOSCALER_SCALE_DOWN_UNNEEDED_TIME: "10m"
    AUTOSCALER_MAX_NODE_PROVISION_TIME: "15m"
    AUTOSCALER_MIN_SIZE_0: "0"
    AUTOSCALER_MAX_SIZE_0: "0"
    AUTOSCALER_MIN_SIZE_1: "0"
    AUTOSCALER_MAX_SIZE_1: "0"
    AUTOSCALER_MIN_SIZE_2: "0"
    AUTOSCALER_MAX_SIZE_2: "0"
